package view;

import java.awt.Color;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author WarisArjuna
 */
public class FormPenghitungKata extends javax.swing.JFrame {

    /**
     * Creates new form FormPenghitungKata
     */
    public FormPenghitungKata() {
    initComponents();
    setLocationRelativeTo(null); // biar frame muncul di tengah layar
    setTitle("Aplikasi Penghitung Kata"); // judul di title bar

    // 🔥 Inisialisasi controller dan model
    new controller.TextAnalyzerController(this, new model.TextAnalyzerModel());
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelJudul = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        panelInput = new javax.swing.JPanel();
        scrollInput = new javax.swing.JScrollPane();
        txtInput = new javax.swing.JTextArea();
        panelHasil = new javax.swing.JPanel();
        lblJudulHasil = new javax.swing.JLabel();
        lblKata = new javax.swing.JLabel();
        lblKarakter = new javax.swing.JLabel();
        lblKalimat = new javax.swing.JLabel();
        lblParagraf = new javax.swing.JLabel();
        lblHasilCari = new javax.swing.JLabel();
        panelBawah = new javax.swing.JPanel();
        lblCari = new javax.swing.JLabel();
        txtCari = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        btnHitung = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(248, 250, 252));
        setPreferredSize(new java.awt.Dimension(700, 500));
        setResizable(false);

        panelJudul.setBackground(new java.awt.Color(204, 232, 255));
        panelJudul.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 0, 10, 0));
        panelJudul.setPreferredSize(new java.awt.Dimension(700, 50));

        lblTitle.setBackground(new java.awt.Color(204, 232, 255));
        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(33, 33, 33));
        lblTitle.setText("Aplikasi Penghitung Kata");
        lblTitle.setOpaque(true);
        panelJudul.add(lblTitle);

        getContentPane().add(panelJudul, java.awt.BorderLayout.NORTH);

        panelInput.setBackground(new java.awt.Color(255, 255, 255));
        panelInput.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        panelInput.setOpaque(false);
        panelInput.setPreferredSize(new java.awt.Dimension(520, 370));
        panelInput.setLayout(new java.awt.BorderLayout());

        scrollInput.setBackground(new java.awt.Color(255, 255, 255));
        scrollInput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        scrollInput.setPreferredSize(new java.awt.Dimension(520, 370));

        txtInput.setBackground(new java.awt.Color(255, 255, 255));
        txtInput.setColumns(20);
        txtInput.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtInput.setForeground(new java.awt.Color(150, 150, 150));
        txtInput.setLineWrap(true);
        txtInput.setRows(10);
        txtInput.setText("Ketik teks di sini...");
        txtInput.setWrapStyleWord(true);
        txtInput.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        txtInput.setPreferredSize(new java.awt.Dimension(500, 350));
        txtInput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtInputFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtInputFocusLost(evt);
            }
        });
        scrollInput.setViewportView(txtInput);

        panelInput.add(scrollInput, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelInput, java.awt.BorderLayout.CENTER);

        panelHasil.setBackground(new java.awt.Color(245, 247, 250));
        panelHasil.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        panelHasil.setPreferredSize(new java.awt.Dimension(180, 370));
        panelHasil.setLayout(new java.awt.GridLayout(6, 6, 1, 6));

        lblJudulHasil.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblJudulHasil.setForeground(new java.awt.Color(51, 51, 51));
        lblJudulHasil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJudulHasil.setText("Hasil Perhitungan");
        panelHasil.add(lblJudulHasil);

        lblKata.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblKata.setForeground(new java.awt.Color(51, 51, 51));
        lblKata.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKata.setText("Kata :");
        panelHasil.add(lblKata);

        lblKarakter.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblKarakter.setForeground(new java.awt.Color(51, 51, 51));
        lblKarakter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKarakter.setText("Karakter :");
        panelHasil.add(lblKarakter);

        lblKalimat.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblKalimat.setForeground(new java.awt.Color(51, 51, 51));
        lblKalimat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKalimat.setText("Kalimat :");
        panelHasil.add(lblKalimat);

        lblParagraf.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblParagraf.setForeground(new java.awt.Color(51, 51, 51));
        lblParagraf.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblParagraf.setText("Paragraf : ");
        panelHasil.add(lblParagraf);

        lblHasilCari.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblHasilCari.setForeground(new java.awt.Color(51, 51, 51));
        lblHasilCari.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHasilCari.setText("Kata Ditemukan : 0 kali");
        panelHasil.add(lblHasilCari);

        getContentPane().add(panelHasil, java.awt.BorderLayout.EAST);

        panelBawah.setBackground(new java.awt.Color(227, 242, 253));
        panelBawah.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(144, 202, 249)));
        panelBawah.setPreferredSize(new java.awt.Dimension(700, 80));
        panelBawah.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));

        lblCari.setBackground(new java.awt.Color(227, 242, 253));
        lblCari.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblCari.setForeground(new java.awt.Color(51, 51, 51));
        lblCari.setText("Cari Kata :");
        lblCari.setOpaque(true);
        panelBawah.add(lblCari);

        txtCari.setBackground(new java.awt.Color(255, 255, 255));
        txtCari.setForeground(new java.awt.Color(33, 33, 33));
        txtCari.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));
        txtCari.setPreferredSize(new java.awt.Dimension(120, 30));
        txtCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCariActionPerformed(evt);
            }
        });
        panelBawah.add(txtCari);

        btnCari.setBackground(new java.awt.Color(33, 150, 243));
        btnCari.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnCari.setForeground(new java.awt.Color(255, 255, 255));
        btnCari.setText("Cari");
        btnCari.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelBawah.add(btnCari);

        btnHitung.setBackground(new java.awt.Color(76, 175, 80));
        btnHitung.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnHitung.setForeground(new java.awt.Color(255, 255, 255));
        btnHitung.setText("Hitung");
        btnHitung.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });
        panelBawah.add(btnHitung);

        btnSimpan.setBackground(new java.awt.Color(255, 152, 0));
        btnSimpan.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("Simpan");
        btnSimpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        panelBawah.add(btnSimpan);

        getContentPane().add(panelBawah, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtInputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtInputFocusGained
        if (txtInput.getText().equals("Ketik teks di sini...")) {
            txtInput.setText("");
            txtInput.setForeground(new Color(33, 33, 33));
        }
    }//GEN-LAST:event_txtInputFocusGained

    private void txtInputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtInputFocusLost
            if (txtInput.getText().isBlank()) {
            txtInput.setText("Ketik teks di sini...");
            txtInput.setForeground(new Color(150, 150, 150));
        }
    }//GEN-LAST:event_txtInputFocusLost

    private void txtCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHitungActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSimpanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPenghitungKata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPenghitungKata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPenghitungKata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPenghitungKata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPenghitungKata().setVisible(true);
            }
        });
    }
    
    // Getter untuk tombol
    public javax.swing.JButton getBtnCari() { return btnCari; }
    public javax.swing.JButton getBtnHitung() { return btnHitung; }
    public javax.swing.JButton getBtnSimpan() { return btnSimpan; }

    // Getter untuk input
    public javax.swing.JTextArea getTxtInput() { return txtInput; }
    public javax.swing.JTextField getTxtCari() { return txtCari; }

    // Getter untuk label hasil
    public javax.swing.JLabel getLblKata() { return lblKata; }
    public javax.swing.JLabel getLblKarakter() { return lblKarakter; }
    public javax.swing.JLabel getLblKalimat() { return lblKalimat; }
    public javax.swing.JLabel getLblParagraf() { return lblParagraf; }
    public javax.swing.JLabel getLblHasilCari() { return lblHasilCari; }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JLabel lblCari;
    private javax.swing.JLabel lblHasilCari;
    private javax.swing.JLabel lblJudulHasil;
    private javax.swing.JLabel lblKalimat;
    private javax.swing.JLabel lblKarakter;
    private javax.swing.JLabel lblKata;
    private javax.swing.JLabel lblParagraf;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel panelBawah;
    private javax.swing.JPanel panelHasil;
    private javax.swing.JPanel panelInput;
    private javax.swing.JPanel panelJudul;
    private javax.swing.JScrollPane scrollInput;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextArea txtInput;
    // End of variables declaration//GEN-END:variables
}
